# Site settings
title: sios13
email: so222et@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
    En blogg om webbteknologier och programmering.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://sios13.github.io/" # the base hostname & protocol for your site
github_username: sios13

# Build settings
markdown: kramdown

months:
    - Januari
    - Februari
    - Mars
    - April
    - Maj
    - Juni
    - Juil
    - Augusti
    - September
    - Oktober
    - November
    - December
